name: CI
# Controls when the workflow will run
on:
  release:
    types: [published]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build_on_macos:
    runs-on: macos-latest
    steps:
      # Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3
        with: 
          path: Blaize_V3  

      # Install dependencies
      - name: Download and install Processing 4 beta
        run: |
          wget -q https://github.com/processing/processing4/releases/download/processing-1282-4.0b7/processing-4.0b7-macos-x64.zip -O ~/Downloads/Processing.zip
          tar -xf ~/Downloads/Processing.zip -C /Applications/
          chmod +x $GITHUB_WORKSPACE/Blaize_V3/.github/workflows/processing-java
      
      # Export for different platforms
      - name: macos-x86_64 export 
        run: |
          $GITHUB_WORKSPACE/Blaize_V3/.github/workflows/processing-java --sketch=$GITHUB_WORKSPACE/Blaize_V3 --output=$GITHUB_WORKSPACE/Blaize_${GITHUB_REF#refs/tags/}_macos-x86_64 --variant=macos-x86_64 --export
          zip -rq Blaize_${GITHUB_REF#refs/tags/}_macos-x86_64.zip Blaize_${GITHUB_REF#refs/tags/}_macos-x86_64/ -x "Blaize_${GITHUB_REF#refs/tags/}_macos-x86_64/source/*"
      - name: macos-aarch64 export
        run: |
          $GITHUB_WORKSPACE/Blaize_V3/.github/workflows/processing-java --sketch=$GITHUB_WORKSPACE/Blaize_V3 --output=$GITHUB_WORKSPACE/Blaize_${GITHUB_REF#refs/tags/}_macos-aarch64 --variant=macos-aarch64 --export
          zip -rq Blaize_${GITHUB_REF#refs/tags/}_macos-aarch64.zip Blaize_${GITHUB_REF#refs/tags/}_macos-aarch64/ -x "Blaize_${GITHUB_REF#refs/tags/}_macos-aarch64/source/*"
      - name: linux-amd64 export
        run: |
          $GITHUB_WORKSPACE/Blaize_V3/.github/workflows/processing-java --sketch=$GITHUB_WORKSPACE/Blaize_V3 --output=$GITHUB_WORKSPACE/Blaize_${GITHUB_REF#refs/tags/}_linux-amd64 --variant=linux-amd64 --export
          zip -rq Blaize_${GITHUB_REF#refs/tags/}_linux-amd64.zip Blaize_${GITHUB_REF#refs/tags/}_linux-amd64/ -x "Blaize_${GITHUB_REF#refs/tags/}_linux-amd64/source/*"
      - name: linux-arm export
        run: |
          $GITHUB_WORKSPACE/Blaize_V3/.github/workflows/processing-java --sketch=$GITHUB_WORKSPACE/Blaize_V3 --output=$GITHUB_WORKSPACE/Blaize_${GITHUB_REF#refs/tags/}_linux-arm --variant=linux-arm --export
          zip -rq Blaize_${GITHUB_REF#refs/tags/}_linux-arm.zip Blaize_${GITHUB_REF#refs/tags/}_linux-arm/ -x "Blaize_${GITHUB_REF#refs/tags/}_linux-arm/source/*"
      - name: linux-aarch64 export
        run: |
          $GITHUB_WORKSPACE/Blaize_V3/.github/workflows/processing-java --sketch=$GITHUB_WORKSPACE/Blaize_V3 --output=$GITHUB_WORKSPACE/Blaize_${GITHUB_REF#refs/tags/}_linux-aarch64 --variant=linux-aarch64 --export
          zip -rq Blaize_${GITHUB_REF#refs/tags/}_linux-aarch64.zip Blaize_${GITHUB_REF#refs/tags/}_linux-aarch64/ -x "Blaize_${GITHUB_REF#refs/tags/}_linux-aarch64/source/*"

      # Upload assets to created release
      - name: Upload release assets 
        run: > 
          cd $GITHUB_WORKSPACE/Blaize_V3

          gh release upload ${GITHUB_REF#refs/tags/} 
          $GITHUB_WORKSPACE/Blaize_${GITHUB_REF#refs/tags/}_macos-x86_64.zip
          $GITHUB_WORKSPACE/Blaize_${GITHUB_REF#refs/tags/}_macos-aarch64.zip
          $GITHUB_WORKSPACE/Blaize_${GITHUB_REF#refs/tags/}_linux-amd64.zip
          $GITHUB_WORKSPACE/Blaize_${GITHUB_REF#refs/tags/}_linux-arm.zip
          $GITHUB_WORKSPACE/Blaize_${GITHUB_REF#refs/tags/}_linux-aarch64.zip
          --clobber
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # This workflow contains a single job called "build"
  build_on_ubuntu:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3
        with: 
          path: Blaize_V3 

      - name: Download and install Processing 3
        run: |
          wget https://github.com/processing/processing/releases/download/processing-0270-3.5.4/processing-3.5.4-linux64.tgz
          tar zxvf processing-3.5.4-linux64.tgz
          cd processing-3.5.4
          ./install.sh
      
      - name: Install 32bit libs
        run: sudo apt update && sudo apt install lib32z1
      
      - name: windows export
        run: |
          $GITHUB_WORKSPACE/processing-3.5.4/processing-java --sketch=$GITHUB_WORKSPACE/Blaize_V3 --output=$GITHUB_WORKSPACE/Blaize_${GITHUB_REF#refs/tags/}_windows --platform=windows --export;
          zip -rq Blaize_${GITHUB_REF#refs/tags/}_windows.zip Blaize_${GITHUB_REF#refs/tags/}_windows/ -x "Blaize_${GITHUB_REF#refs/tags/}_windows/source/*"
      
      # Upload assets to created release
      - name: Upload release assets 
        run: > 
          cd $GITHUB_WORKSPACE/Blaize_V3

          gh release upload ${GITHUB_REF#refs/tags/} 
          $GITHUB_WORKSPACE/Blaize_${GITHUB_REF#refs/tags/}_windows.zip
          --clobber
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
